# -*- coding: utf-8 -*-
"""Running EC2 with LocalStack Using Docker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T8VRiEYAFtKjy-FkfJrlwY2pKw6sLzfq

# Running EC2 menggunakan LocalStack dengan Docker Desktop

Running LocalStack on Docker
"""

docker run --rm -it -p 4566:4566 -p 4571:4571 localstack/localstack

"""Masuk Ke dalam Container"""

docker exec -it localstack bash

"""Memetakan port ke host"""

docker stop inspiring_mahavira # ganti sesuai container
docker rm inspiring_mahavira
docker run -d --name inspiring_mahavira -p 8000:8000 -p 4566:4566 localstack/localstack

"""Clone Fask API ke dalam Container"""

apt update
apt install -y python3 python3-pip curl git
git clone https://gitlab.com/HarshCasper/flask-api-example.git
cd flask-api-example
pip3 install flask

"""Jalankan Flask API"""

python3 app.py --host=0.0.0.0 --port=8000

# Jika ingin menjalankannya di background
nohup python3 app.py --host=0.0.0.0 --port=8000 &

"""Jika Berhasil hasilnya akan menampilkan ini
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://172.17.0.2:8000

Cek API
"""

curl http://localhost:8000/

"""Atau Buka pada Browser"""

http://localhost:8000/

"""Untuk percobaan Additional kirim GET dan POST"""

# get
curl http://localhost:8000/get

# post
curl -X POST -H "Content-Type: application/json" -d '{"key": "value"}' http://localhost:8000/post